apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argooperatorrole
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - "*"
    verbs:
      - get
      - patch
      - create 
      - list 
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argooperatorrole
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - "*"
    verbs:
      - get
      - patch
      - create 
      - list 
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argooperator
  namespace: argo
secrets:
  - name: argooperator-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: argooperator-sa
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argooperator
type: kubernetes.io/service-account-token