apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-build
spec:
  templates:
    # TODO: use snapshot images and cache.
    - name: docker-kaniko-build
      inputs:
        parameters:
          - name: image-repository-path
          - name: image-tag
          - name: dockerfile
            value: "dockerfile" # Default value
          - name: docker-context
            value: "/workdir/src" # Default value
      container:
        image: gcr.io/kaniko-project/executor:v1.9.0-debug
        command: ["/kaniko/executor"]
        args:
          [
            "--dockerfile={{inputs.parameters.dockerfile}}",
            "--context={{inputs.parameters.docker-context}}",
            "--destination={{inputs.parameters.image-repository-path}}:{{inputs.parameters.image-tag}}",
            "--digest-file=/tmp/docker-image-digest.txt",
            "--cache=false", 
          ]
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/config.json
            subPath: .dockerconfigjson
          - name: repo-root
            mountPath: /workdir
      outputs:
        parameters:
        - name: docker-image-digest
          valueFrom:
            path: /tmp/docker-image-digest.txt