
# ServiceAccount in argo namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-deployer
  namespace: argo
---
# ClusterRole for cross-namespace permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-deployer-clusterrole
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "services", "pods"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
# RoleBinding in app namespace binding argo ServiceAccount to ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-deployer-binding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: argo-deployer
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-deployer-clusterrole
  apiGroup: rbac.authorization.k8s.io
