apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-deployer
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-deployer-role
  namespace: app
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "services", "pods"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-deployer-binding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: argo-deployer
roleRef:
  kind: Role
  name: argo-deployer-role
  apiGroup: rbac.authorization.k8s.io
