apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: go-api-integration-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      Test and Build my golang API 
spec:
  serviceAccountName: argo-workflows-sa
  volumeClaimTemplates:
    - metadata:
        name: repo-root
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  volumes:
    - name: docker-config
      secret:
        secretName: ghcr-cred
  arguments:
    parameters:
      - name: git-repo-url
        value: git@github.com:ItaiMelamed/go-rest-api-project.git
      - name: git-revision
        value: dev
      - name: git-clone-path
        value: "/workdir/src"
      - name: docker-image-path
        value: ghcr.io/itaimelamed/golang-gin-api
      - name: project-root
        value: "/workdir"
      - name: deployment-file-path
        value: ci/deployment.yaml
  entrypoint: cicd
  templates:
    - name: cicd
      steps:
        - - name: checkout
            templateRef:
              name: checkout
              template: checkout
            arguments:
              parameters:
                - name: git-repo-url
                  value: "{{workflow.parameters.git-repo-url}}"
                - name: git-revision
                  value: "{{workflow.parameters.git-revision}}"
                - name: clone-path
                  value: "{{workflow.parameters.git-clone-path}}"
                - name: git-secret-name
                  value: "git-creds"

        - - name: kaniko-build
            templateRef:
              name: docker-build
              template: docker-kaniko-build
            arguments:
              parameters:
                - name: image-repository-path
                  value: "{{workflow.parameters.docker-image-path}}"
                - name: image-tag
                  value: "{{steps.checkout.outputs.parameters.git-commit-short-sha}}"
                - name: docker-context
                  value: "{{workflow.parameters.git-clone-path}}"

        - - name: deploy
            templateRef:
              name: deploy
              template: deploy-using-k8s-file
            arguments:
              parameters:
                - name: docker-image-name
                  value: "{{workflow.parameters.docker-image-path}}"
                - name: docker-image-digest
                  value: "{{steps.kaniko-build.outputs.parameters.docker-image-digest}}"
                - name: project-root
                  value: "/workdir/src"
                - name: deployment-file-path
                  value: ci/deployment.yaml