apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-rb
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflows
  apiGroup: rbac.authorization.k8s.io
